"""
gt_temporal_from_roots.py — Generate proper gt_temporal.jsonl from GTBuilder output.

The EXISTING gt_temporal.jsonl was generated by dumping raw OSV `introduced` events,
which produces:
  - 73% entries with version "0" (OSV's "from the beginning" marker)
  - 10% entries with git commit hashes (GIT range events, not version numbers)
  - Empty version_sequence for ALL entries
  - Null timestamps for ALL entries
  - Massive duplication: 5981 rows from 79 CVEs (each affected[] entry → one row)

This script generates proper GT by:
  1. Using GTBuilder.build_root_causes() which resolves versions through the graph
  2. Converting RootCause objects to temporal GT format
  3. Building version sequences from the dependency graph
  4. Populating timestamps from graph node attributes
  5. Handling "introduced: 0" by mapping to earliest known graph version
  6. Deduplicating properly
  7. Computing real time_lag_days between origin and discovered versions

Usage:
    python gt_temporal_from_roots.py \\
        --dep-graph data/dep_graph_cve.pkl \\
        --cve-meta data/cve_records_for_meta.pkl \\
        --output data/gt_temporal_fixed.jsonl \\
        [--raw-osv-fallback]  # also include filtered raw OSV entries for coverage
"""

import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent.parent))

import json
import pickle
import re
import argparse
import time as time_module
from collections import defaultdict
from typing import Dict, List, Optional, Tuple, Set
from datetime import datetime, timezone


# ==========================================================================
# Package index from graph (handles Maven coordinates)
# ==========================================================================

def _extract_pkg_ver_from_release(release: str) -> Tuple[Optional[str], Optional[str]]:
    """Parse Maven coordinate groupId:artifactId:version → (simplified_pkg, version)."""
    if not release:
        return None, None
    parts = release.split(':')
    if len(parts) >= 3:
        artifact = parts[1]
        version = parts[2]
        # Simplify: tomcat-catalina → tomcat
        simple = artifact.split('-')[0] if '-' in artifact else artifact
        return simple, version
    elif len(parts) == 2:
        return parts[0], parts[1]
    return None, None


def build_package_index(graph) -> Dict[str, List[dict]]:
    """
    Build {package_name: [sorted list of {version, node_id, timestamp, release}]}
    from the networkx dependency graph.
    """
    pkg_index = defaultdict(list)

    for nid in graph.nodes():
        nd = graph.nodes[nid]
        release = nd.get('release', '')
        simple_pkg, version = _extract_pkg_ver_from_release(release)
        if not simple_pkg or not version:
            continue

        ts = nd.get('timestamp', 0)
        entry = {
            'version': version,
            'node_id': nid,
            'timestamp': ts,
            'release': release,
        }

        pkg_index[simple_pkg].append(entry)

        # Also index by full artifact_id
        parts = release.split(':')
        if len(parts) >= 3:
            full_artifact = parts[1]
            if full_artifact != simple_pkg:
                pkg_index[full_artifact].append(entry)

    # Sort by timestamp
    for pkg in pkg_index:
        pkg_index[pkg].sort(key=lambda x: x['timestamp'])

    return dict(pkg_index)


def build_version_sequence(pkg_index: Dict, package: str) -> List[str]:
    """Get ordered, deduplicated version list for a package."""
    entries = _resolve_package_entries(pkg_index, package)
    seen = set()
    seq = []
    for e in entries:
        if e['version'] not in seen:
            seen.add(e['version'])
            seq.append(e['version'])
    return seq


def _resolve_package_entries(pkg_index: Dict, package: str) -> List[dict]:
    """Find package entries, with fuzzy fallback."""
    entries = pkg_index.get(package, [])
    if entries:
        return entries
    # Fuzzy: case-insensitive substring
    pkg_lower = package.lower()
    for key in pkg_index:
        if pkg_lower in key.lower() or key.lower() in pkg_lower:
            return pkg_index[key]
    return []


def find_timestamp(pkg_index: Dict, package: str, version: str) -> Optional[float]:
    """Find timestamp for package@version."""
    entries = _resolve_package_entries(pkg_index, package)
    for e in entries:
        if e['version'] == version:
            return e['timestamp']
    # Fuzzy version match: strip trailing .0
    v = version
    while v.endswith('.0') and len(v) > 1:
        v = v[:-2]
        for e in entries:
            if e['version'] == v:
                return e['timestamp']
    return None


def find_earliest_version(pkg_index: Dict, package: str) -> Optional[str]:
    """Find earliest version by timestamp."""
    entries = _resolve_package_entries(pkg_index, package)
    if not entries:
        return None
    return entries[0]['version']  # already sorted by timestamp


def find_discovered_version(pkg_index: Dict, package: str) -> Optional[str]:
    """Find latest/discovered version by timestamp."""
    entries = _resolve_package_entries(pkg_index, package)
    if not entries:
        return None
    return entries[-1]['version']


# ==========================================================================
# OSV event parser (improved)
# ==========================================================================

def parse_osv_events(record: dict) -> List[dict]:
    """
    Parse OSV affected[].ranges[].events into structured (introduced, fixed) pairs.
    
    Returns list of:
        {
            'package': str,
            'introduced': str,
            'fixed': str or None,
            'range_type': 'SEMVER' | 'ECOSYSTEM' | 'GIT',
            'ecosystem': str,
        }
    """
    results = []

    for af in record.get('affected', []) or []:
        pkg_obj = af.get('package', {}) or {}
        pkg_name = pkg_obj.get('name', '')
        ecosystem = pkg_obj.get('ecosystem', '')

        for rng in af.get('ranges', []) or []:
            range_type = rng.get('type', '')
            events = rng.get('events', []) or []

            cur_intro = None
            for ev in events:
                if 'introduced' in ev and ev['introduced'] not in (None, ''):
                    cur_intro = ev['introduced']
                elif 'fixed' in ev and ev['fixed'] not in (None, '') and cur_intro is not None:
                    results.append({
                        'package': pkg_name,
                        'introduced': cur_intro,
                        'fixed': ev['fixed'],
                        'range_type': range_type,
                        'ecosystem': ecosystem,
                    })
                    cur_intro = None

            # Open-ended range (introduced but no fix)
            if cur_intro is not None:
                results.append({
                    'package': pkg_name,
                    'introduced': cur_intro,
                    'fixed': None,
                    'range_type': range_type,
                    'ecosystem': ecosystem,
                })

    return results


def classify_version(ver: str) -> str:
    """Classify a version string: 'semver', 'zero', 'commit', 'unknown'."""
    if ver == '0':
        return 'zero'
    if re.match(r'^[0-9a-f]{20,}$', ver):
        return 'commit'
    if re.match(r'^\d+[\.\d]*', ver):
        return 'semver'
    return 'unknown'


# ==========================================================================
# GT entry builder
# ==========================================================================

def build_gt_entry(
    cve_id: str,
    package: str,
    origin_version: str,
    discovered_version: str,
    pkg_index: Dict,
    method: str = 'osv_introduced',
    evidence: str = '',
    confidence: float = 0.9,
) -> Optional[dict]:
    """Build a single GT temporal entry with all fields properly populated."""

    version_seq = build_version_sequence(pkg_index, package)

    origin_ts = find_timestamp(pkg_index, package, origin_version)
    disc_ts = find_timestamp(pkg_index, package, discovered_version)

    time_lag_days = 0
    if origin_ts and disc_ts:
        time_lag_days = abs(disc_ts - origin_ts) / (24 * 3600)

    return {
        'cve_id': cve_id,
        'package': package,
        'origin_version': f"{package}@{origin_version}",
        'discovered_version': f"{package}@{discovered_version}",
        'version_sequence': version_seq,
        'confidence': confidence,
        'method': method,
        'evidence': evidence,
        'time_lag_days': round(time_lag_days, 2),
        'origin_timestamp': origin_ts,
        'discovered_timestamp': disc_ts,
        'source': 'automatic',
    }


# ==========================================================================
# Strategy 1: From GTBuilder root_causes.jsonl
# ==========================================================================

def gt_from_root_causes(roots_path: str, pkg_index: Dict) -> List[dict]:
    """Convert root_causes.jsonl → gt_temporal entries."""
    entries = []
    roots = []
    with open(roots_path, 'r') as f:
        for line in f:
            line = line.strip()
            if line:
                roots.append(json.loads(line))

    print(f"  Loaded {len(roots)} root causes")

    for root in roots:
        cve_id = root['cve_id']
        package = root['package']
        version = root['version']

        if not version:
            continue

        vtype = classify_version(version)

        if vtype == 'zero':
            # Map to earliest known version
            earliest = find_earliest_version(pkg_index, package)
            if earliest:
                version = earliest
                method = 'gtbuilder_remapped_zero'
                evidence = f"Original 'introduced: 0' remapped to earliest: {earliest}"
            else:
                continue  # Can't resolve
        elif vtype == 'commit':
            continue  # Skip commit hashes
        elif vtype == 'semver':
            method = 'gtbuilder_resolved'
            evidence = f"Resolved by GTBuilder from OSV/NVD records"
        else:
            continue

        # Find a reasonable discovered version (latest with CVE)
        disc_ver = find_discovered_version(pkg_index, package)
        if not disc_ver:
            continue

        entry = build_gt_entry(
            cve_id=cve_id,
            package=package,
            origin_version=version,
            discovered_version=disc_ver,
            pkg_index=pkg_index,
            method=method,
            evidence=evidence,
            confidence=root.get('confidence', 0.9),
        )
        if entry:
            entries.append(entry)

    return entries


# ==========================================================================
# Strategy 2: From raw OSV/CVE records (improved version of the broken script)
# ==========================================================================

def gt_from_osv_records(cve_meta: dict, pkg_index: Dict) -> List[dict]:
    """
    Generate GT from OSV records, but properly:
    - Filter GIT ranges (commit hashes)
    - Handle 'introduced: 0' → earliest graph version
    - Deduplicate at (cve_id, package, origin_version) level
    - Populate version sequences and timestamps
    """
    entries = []
    seen = set()
    _dbg = {'total_records': 0, 'has_affected': 0, 'osv_events': 0,
            'git_skipped': 0, 'commit_skipped': 0, 'zero_remapped': 0,
            'semver_kept': 0, 'no_disc_ver': 0, 'deduped': 0,
            'no_cve_id': 0}

    # ----------------------------------------------------------------
    # Flatten cve_meta into a list of (cve_id, osv_data_dict) pairs.
    # cve_meta layout (from your pickle):
    #   keys   = graph node IDs  (NOT CVE IDs!)
    #   values = [ { 'name': 'BIT-...', 'builder_payload': { 'affected':..., 'aliases':['CVE-...'] }, 'source':'osv' }, ... ]
    # ----------------------------------------------------------------
    pairs = []  # (cve_id, osv_dict_with_affected)

    all_records = []
    if isinstance(cve_meta, dict):
        for _key, val in cve_meta.items():
            if isinstance(val, list):
                all_records.extend(val)
            elif isinstance(val, dict):
                all_records.append(val)
    elif isinstance(cve_meta, list):
        all_records = cve_meta

    for record in all_records:
        if not isinstance(record, dict):
            continue

        # --- Find the sub-dict that contains 'affected' ---
        data = None
        for candidate in [
            record.get('builder_payload'),   # your format: affected is here
            record.get('data'),              # alternative format
            record,                          # record itself
        ]:
            if isinstance(candidate, dict) and 'affected' in candidate:
                data = candidate
                break

        if not data:
            continue

        # --- Extract CVE ID ---
        cve_id = None
        # Try aliases first (most reliable)
        for alias in (data.get('aliases') or []):
            if isinstance(alias, str) and alias.startswith('CVE-'):
                cve_id = alias
                break
        # Try name field: 'BIT-jenkins-2023-36478' → extract CVE from aliases
        if not cve_id:
            name = record.get('name') or data.get('id') or ''
            if name.startswith('CVE-'):
                cve_id = name
        # Try top-level
        if not cve_id:
            cve_id = record.get('cve_id') or record.get('id')

        if not cve_id or not cve_id.startswith('CVE-'):
            _dbg['no_cve_id'] += 1
            continue

        pairs.append((cve_id, data))

    print(f"  Found {len(pairs)} records with CVE IDs and 'affected' data")
    print(f"  (skipped {_dbg['no_cve_id']} records without CVE IDs)")

    for cve_id, data in pairs:
        _dbg['total_records'] += 1

        osv_events = parse_osv_events(data)
        _dbg['osv_events'] += len(osv_events)

        for ev in osv_events:
            # Skip GIT ranges entirely
            if ev['range_type'] == 'GIT':
                _dbg['git_skipped'] += 1
                continue

            introduced = ev['introduced']
            fixed = ev.get('fixed')
            raw_pkg = ev['package']

            # Normalize package name
            if ':' in raw_pkg:
                package = raw_pkg.split(':')[-1]
            elif '/' in raw_pkg:
                package = raw_pkg.split('/')[-1]
            else:
                package = raw_pkg
            package = package.lower()

            # Further simplify: tomcat-catalina → tomcat
            if '-' in package:
                simple = package.split('-')[0]
                # Use simplified name if it exists in index
                if simple in pkg_index and package not in pkg_index:
                    package = simple

            vtype = classify_version(introduced)

            if vtype == 'zero':
                earliest = find_earliest_version(pkg_index, package)
                if earliest:
                    origin_ver = earliest
                    method = 'osv_introduced_remapped'
                    evidence = f"'introduced: 0' remapped to earliest graph version: {earliest}"
                    _dbg['zero_remapped'] += 1
                else:
                    continue
            elif vtype == 'semver':
                origin_ver = introduced
                method = 'osv_introduced'
                evidence = f"OSV introduced version: {introduced}"
                _dbg['semver_kept'] += 1
            elif vtype == 'commit':
                _dbg['commit_skipped'] += 1
                continue
            else:
                continue

            # Discovered version
            if fixed and classify_version(fixed) == 'semver':
                disc_ver = fixed
            else:
                disc_ver = find_discovered_version(pkg_index, package)
                if not disc_ver:
                    _dbg['no_disc_ver'] += 1
                    continue

            # Deduplicate
            dedup_key = (cve_id, package, origin_ver)
            if dedup_key in seen:
                _dbg['deduped'] += 1
                continue
            seen.add(dedup_key)

            entry = build_gt_entry(
                cve_id=cve_id,
                package=package,
                origin_version=origin_ver,
                discovered_version=disc_ver,
                pkg_index=pkg_index,
                method=method,
                evidence=evidence,
                confidence=0.9,
            )
            if entry:
                entries.append(entry)

    print(f"  [DEBUG] Record processing stats: {json.dumps(_dbg, indent=2)}")
    return entries


# ==========================================================================
# Main
# ==========================================================================

def main():
    parser = argparse.ArgumentParser(
        description="Generate proper gt_temporal.jsonl from GTBuilder or OSV records"
    )
    parser.add_argument('--dep-graph', required=True, help="Dependency graph pickle")
    parser.add_argument('--cve-meta', default=None, help="CVE metadata pickle")
    parser.add_argument('--roots', default=None, help="GTBuilder root_causes.jsonl (if already built)")
    parser.add_argument('--output', required=True, help="Output JSONL path")
    parser.add_argument('--raw-osv-fallback', action='store_true',
                        help="Also include entries from raw OSV parsing")
    parser.add_argument('--stats', default=None, help="Output stats JSON")

    args = parser.parse_args()

    t0 = time_module.time()

    # --- Load graph ---
    print("Loading dependency graph...")
    with open(args.dep_graph, 'rb') as f:
        graph = pickle.load(f)
    print(f"  {graph.number_of_nodes()} nodes, {graph.number_of_edges()} edges")

    # --- Build package index ---
    print("Building package index...")
    pkg_index = build_package_index(graph)
    print(f"  {len(pkg_index)} package identifiers")

    # Show coverage
    sample_pkgs = sorted(pkg_index.keys())[:15]
    print(f"  Sample: {sample_pkgs}")
    total_versions = sum(len(v) for v in pkg_index.values())
    print(f"  Total version entries: {total_versions}")

    # --- Generate GT entries ---
    all_entries = []

    # Strategy 1: From pre-built root_causes.jsonl
    if args.roots:
        print(f"\nGenerating GT from root_causes.jsonl...")
        root_entries = gt_from_root_causes(args.roots, pkg_index)
        print(f"  Generated {len(root_entries)} entries from root causes")
        all_entries.extend(root_entries)

    # Strategy 2: From raw OSV records in cve_meta
    if args.cve_meta and (args.raw_osv_fallback or not args.roots):
        print(f"\nGenerating GT from CVE metadata (OSV records)...")
        with open(args.cve_meta, 'rb') as f:
            cve_meta = pickle.load(f)
        print(f"  Loaded {len(cve_meta)} CVE metadata entries")

        osv_entries = gt_from_osv_records(cve_meta, pkg_index)
        print(f"  Generated {len(osv_entries)} entries from OSV records")

        # Merge (dedup against existing)
        existing_keys = set((e['cve_id'], e['origin_version']) for e in all_entries)
        new = [e for e in osv_entries if (e['cve_id'], e['origin_version']) not in existing_keys]
        print(f"  {len(new)} new entries after dedup with root_causes")
        all_entries.extend(new)

    # --- Final deduplication ---
    seen = set()
    deduped = []
    for e in all_entries:
        key = (e['cve_id'], e['origin_version'])
        if key not in seen:
            seen.add(key)
            deduped.append(e)
    all_entries = deduped

    # --- Quality stats ---
    has_seq = sum(1 for e in all_entries if e.get('version_sequence'))
    has_ts = sum(1 for e in all_entries if e.get('origin_timestamp'))
    unique_cves = len(set(e['cve_id'] for e in all_entries))
    unique_pkgs = len(set(e['package'] for e in all_entries))

    print(f"\n{'='*60}")
    print(" GT TEMPORAL SUMMARY ".center(60, '='))
    print(f"{'='*60}")
    print(f"  Total entries:              {len(all_entries)}")
    print(f"  Unique CVEs:                {unique_cves}")
    print(f"  Unique packages:            {unique_pkgs}")
    print(f"  With version_sequence:      {has_seq}/{len(all_entries)}")
    print(f"  With origin_timestamp:      {has_ts}/{len(all_entries)}")
    print(f"  Time: {time_module.time() - t0:.1f}s")
    print(f"{'='*60}")

    # --- Write output ---
    Path(args.output).parent.mkdir(parents=True, exist_ok=True)
    with open(args.output, 'w') as f:
        for entry in all_entries:
            f.write(json.dumps(entry) + '\n')
    print(f"\n✓ Written to {args.output}")

    # --- Stats ---
    if args.stats:
        stats = {
            'total_entries': len(all_entries),
            'unique_cves': unique_cves,
            'unique_packages': unique_pkgs,
            'with_version_sequence': has_seq,
            'with_origin_timestamp': has_ts,
            'methods': dict(defaultdict(int, {
                e['method']: sum(1 for x in all_entries if x['method'] == e['method'])
                for e in all_entries
            })),
        }
        with open(args.stats, 'w') as f:
            json.dump(stats, f, indent=2)
        print(f"✓ Stats saved to {args.stats}")


if __name__ == '__main__':
    main()